# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "Empact-sexy_pg_constraints"
  s.version = "0.4.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Maxim Chernyak", "Ben Woosley"]
  s.date = "2013-05-02"
  s.description = "Use migrations and simple syntax to manage constraints in PostgreSQL DB."
  s.email = "ben.woosley@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    "CHANGELOG.rdoc",
    "Empact-sexy_pg_constraints.gemspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "init.rb",
    "lib/sexy_pg_constraints.rb",
    "lib/sexy_pg_constraints/constrainers/constrainer.rb",
    "lib/sexy_pg_constraints/constrainers/deconstrainer.rb",
    "lib/sexy_pg_constraints/constrainers/helpers.rb",
    "lib/sexy_pg_constraints/constraints.rb",
    "lib/sexy_pg_constraints/railtie.rb",
    "lib/sexy_pg_constraints/schema_definitions.rb"
  ]
  s.homepage = "https://github.com/Empact/sexy_pg_constraints"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = nil

  s.metadata["allowed_push_host"] = "https://packagecloud.io"
  s.add_development_dependency "test-unit"

  s.add_runtime_dependency(%q<activerecord>, [">= 3.0.0"])
  s.add_development_dependency(%q<pg>, [">= 0"])
  s.add_development_dependency(%q<shoulda>, [">= 0"])
  s.add_development_dependency(%q<jeweler>, [">= 0"])
end

